INSERT INTO marcas (nombre) VALUES('ACER');
INSERT INTO marcas (nombre) VALUES('TOSHIBA');
INSERT INTO marcas (nombre) VALUES('LG');
INSERT INTO marcas (nombre) VALUES('EPSON');
INSERT INTO marcas (nombre) VALUES('LENOVO');
INSERT INTO marcas (nombre) VALUES('CISCO');
INSERT INTO marcas (nombre) VALUES('DLINK');
INSERT INTO marcas (nombre) VALUES('SAMSUNG');
INSERT INTO marcas (nombre) VALUES('SONY');
INSERT INTO marcas (nombre) VALUES('INTEL');
INSERT INTO marcas (nombre) VALUES('AMD');
INSERT INTO marcas (nombre) VALUES('LOGITECH');
INSERT INTO marcas (nombre) VALUES('NVIDIA');
INSERT INTO marcas (nombre) VALUES('WESTERN DIGITAL');
INSERT INTO marcas (nombre) VALUES('SEAGATE');
INSERT INTO marcas (nombre) VALUES('JANUS');
INSERT INTO marcas (nombre) VALUES('HITACHI');
INSERT INTO marcas (nombre) VALUES('ASUS');
INSERT INTO marcas (nombre) VALUES('MIKROTIK');
INSERT INTO marcas (nombre) VALUES('UBIQUITI');
INSERT INTO marcas (nombre) VALUES('DELL');
INSERT INTO marcas (nombre) VALUES('CANON');
INSERT INTO marcas (nombre) VALUES('KYOSERA');
INSERT INTO marcas (nombre) VALUES('IBM');
INSERT INTO marcas (nombre) VALUES('KINGSTON');
INSERT INTO marcas (nombre) VALUES('GENIUS');
INSERT INTO marcas (nombre) VALUES('GENERICO');
INSERT INTO marcas (nombre) VALUES('BROTHER');
INSERT INTO marcas (nombre) VALUES('MSI');
INSERT INTO marcas (nombre) VALUES('ASROCK');
INSERT INTO marcas (nombre) VALUES('GIGABYTE');
INSERT INTO marcas (nombre) VALUES('LINKSYS');
INSERT INTO marcas (nombre) VALUES('COMPAG');
INSERT INTO marcas (nombre) VALUES('VERBATIM');
INSERT INTO marcas (nombre) VALUES('LEXMARK');
INSERT INTO marcas (nombre) VALUES('UNITEC');
INSERT INTO marcas (nombre) VALUES('Securegen');
INSERT INTO marcas (nombre) VALUES('SYMBOL');
INSERT INTO marcas (nombre) VALUES('HONEYWELL');
INSERT INTO marcas (nombre) VALUES('PHOENIX');
INSERT INTO marcas (nombre) VALUES('MAXITECH');




INSERT INTO articulos (nombre) VALUES('Disco Duro');
INSERT INTO articulos (nombre) VALUES('Mouse');
INSERT INTO articulos (nombre) VALUES('BOARD');
INSERT INTO articulos (nombre) VALUES('Teclado');
INSERT INTO articulos (nombre) VALUES('Monitor');
INSERT INTO articulos (nombre) VALUES('Maquina Movil');
INSERT INTO articulos (nombre) VALUES('Teléfono Celular');
INSERT INTO articulos (nombre) VALUES('CPU');
INSERT INTO articulos (nombre) VALUES('Memoria RAM');
INSERT INTO articulos (nombre) VALUES( 'Memoria USB');
INSERT INTO articulos (nombre) VALUES( 'Fuente de Poder');
INSERT INTO articulos (nombre) VALUES( 'Tarjeta de Red');
INSERT INTO articulos (nombre) VALUES( 'Tarjeta de TV');
INSERT INTO articulos (nombre) VALUES( 'Tarjeta Grafica');
INSERT INTO articulos (nombre) VALUES( 'Unidad de DVD');
INSERT INTO articulos (nombre) VALUES( 'CD - DVD');
INSERT INTO articulos (nombre) VALUES( 'Cautin');
INSERT INTO articulos (nombre) VALUES( 'Sopladora');
INSERT INTO articulos (nombre) VALUES( 'Camara Web');
INSERT INTO articulos (nombre) VALUES( 'Disipador');
INSERT INTO articulos (nombre) VALUES( 'Cable Paralelo');
INSERT INTO articulos (nombre) VALUES( 'Cable Paralelo a USB');
INSERT INTO articulos (nombre) VALUES( 'Cable VGA');
INSERT INTO articulos (nombre) VALUES( 'Cable de Red');
INSERT INTO articulos (nombre) VALUES( 'Swicth');
INSERT INTO articulos (nombre) VALUES( 'Router');
INSERT INTO articulos (nombre) VALUES( 'Antena');
INSERT INTO articulos (nombre) VALUES( 'Laptop');
INSERT INTO articulos (nombre) VALUES( 'POE');
INSERT INTO articulos (nombre) VALUES( 'Lector Biometrico');
INSERT INTO articulos (nombre) VALUES( 'Lector de Código de Barras');
INSERT INTO articulos (nombre) VALUES( 'Ponchadora');
INSERT INTO articulos (nombre) VALUES( 'Amarras Plasticas');
INSERT INTO articulos (nombre) VALUES( 'Impresora');
INSERT INTO articulos (nombre) VALUES( 'Multimetro');
INSERT INTO articulos (nombre) VALUES( 'Procesador');
INSERT INTO articulos (nombre) VALUES( 'Limpiador Electronico');
INSERT INTO articulos (nombre) VALUES( 'Lubricante 556 CRC');
INSERT INTO articulos (nombre) VALUES( 'Limpiador de Pantalla CRC');
INSERT INTO articulos (nombre) VALUES( 'Cable de datos SATA');
INSERT INTO articulos (nombre) VALUES( 'Convertidor Manhattan');
INSERT INTO articulos (nombre) VALUES( 'Microsoft');


